# Generated by Django 4.2.5 on 2023-09-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('author', models.CharField(max_length=30, verbose_name='Yazar')),
                ('title_image', models.ImageField(upload_to='static/img/blog/', verbose_name='Resim')),
                ('published_date', models.DateField(verbose_name='Tarih')),
                ('first_place', models.TextField(verbose_name='Giriş yazısı')),
                ('quote', models.CharField(max_length=255, verbose_name='Vurgulanan Söz')),
                ('second_place', models.TextField(verbose_name='İkinci bölüm')),
                ('sub_image', models.ImageField(upload_to='static/img/blog/', verbose_name='İkinci Resim')),
                ('finished_place', models.TextField(verbose_name='Kapanış yazısı')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.blogcategories', verbose_name='Kategoriler')),
            ],
        ),
    ]
