# Generated by Django 4.2.5 on 2023-09-24 21:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cityname_project_blogs_slug_alter_blogs_category_and_more'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='blogs',
            name='finished_place',
            field=tinymce.models.HTMLField(verbose_name='Kapanış yazısı'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='first_place',
            field=tinymce.models.HTMLField(verbose_name='Giriş yazısı'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='second_place',
            field=tinymce.models.HTMLField(verbose_name='İkinci Bölüm'),
        ),
    ]
